name: Build Website

on: 
  push:
    branches: 
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Build svelte project
        run: |
          npm install
          npm run build
        
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: build
          fqdn: seth.cx
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
